# Datasource
spring:
  #  H2
  #  datasource:
  #    url: jdbc:h2:file:~/test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #    Heroku postgress
  #  datasource:

  #  datasource:
  #    url: ${JDBC_DATABASE_URL}
  #    username: ${JDBC_DATABASE_USERNAME}
  #    password: ${JDBC_DATABASE_PASSWORD}
  jackson.serialization.INDENT_OUTPUT: true
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
  h2.console:
    enabled: true
    path: /h2
server:
  port: 9999